channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.24.3
  - packaging==23.1
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.11.1
name: mlflow-env
